In [1]:
# Numpy : Numerical Python
# 다차원 배열(array) 빠르게 조작, 계산

import numpy as np
# import : numpy 라이브러리 기능을 불러와서 사용
# as : 별명

np.__version__

'1.18.5'

In [6]:
# Python list(리스트) : 여러개의 데이터를 저장할 수 있는 자료 타입
num_list = [1, 2, 3]
print(type(num_list), num_list)

# numpy array(배열) : 한가지 타입의 데이터 여러개를 저장할 수 있는 자료 타입
num_array = np.array([1, 2, 3])
print(type(num_array))   # ndarray : n-dimensional array
print(num_array)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]


In [10]:
# Python 리스트는 다른 타입의 값들도 함께 저장할 수 있음
list1 = [1, "abc", True]
print(list1)   # 숫자, 문자열, 논리 타입을 함께 저장

# numpy ndarray는 한가지 타입의 값들만 저장할 수 있음
array1 = np.array([1, "abc", True])
print(array1)   # 숫자 1과 논리 타입 True가 문자열로 변환되서 저장
print(array1.dtype)   # Unicode 타입 - 문자열

[1, 'abc', True]
['1' 'abc' 'True']
<U21


In [14]:
# Python 리스트는 + 연산과 * 연산을 사용할 수 있음
# Python 리스트는 -, /, %, // 등의 연산은 제공하지 않음
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)   # 두 개의 리스트를 이어서 붙여줌
print(list1 * 2)   # 곱한 숫자만큼 원소들을 반복해서 리스트의 크기를 늘림

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [19]:
# numpy ndarray는 모든 산술 연산(+, -, *, /, %, //)을 제공
# 같은 위치의 원소들끼리 산술 연산을 수행함
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1.dtype)   # int64 - 정수
print(array1 + array2)
print(array1 - array2)

int64
[5 7 9]
[-3 -3 -3]


In [23]:
# ndarray를 만들어주는 함수들
array3 = np.array([1, 2, 3, 4, 5])
print(array3)

array4 = np.arange(1, 6)   # start <= x < end, 1씩 증가하는 숫자로 이루어진 배열
print(array4)

[1 2 3 4 5]
[1 2 3 4 5]


In [26]:
array5 = np.ones(5, dtype=np.int)
print(array5)
print(array5.shape)   # 1차원 배열(array), 원소 개수 = 5
print(array5.dtype)

[1 1 1 1 1]
(5,)
int64


In [28]:
array6 = np.ones((2,3))   # (2, 3) 
print(array6)
print(array6.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [32]:
array7 = np.zeros((3, 4))   # shape(row, column)
print(array7)
print(array7.shape)
print(len(array7))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
3


In [34]:
array8 = np.eye(3)
# 항등 행렬을 만들어주는 함수
# 항등 행렬 : 대각선의 원소들은 모두 1이고, 나머지는 0으로 채워진 정사각행렬
print(array8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# 난수(random number)로 배열을 만들어 주는 함수들
array9 = np.random.rand(3)   # 0 <= r < 1 난수를 생성
print(array9, array9.shape)

array10 = np.random.rand(2, 3,)
print(array10, array10.shape)

[0.42433029 0.83343967 0.86774036] (3,)
[[0.65218206 0.13730935 0.45843304]
 [0.94925093 0.86283468 0.01648989]] (2, 3)


In [41]:
array11 = np.random.randn(2, 3)
# normal distributuon(정규 분포)을 따르는 난수를 생성
# 정규 분포 : 평균이 0이고, 표준편차가 1인 분포
print(array11)

[[ 1.72955728  1.34239698  0.84803888]
 [-0.42451123  1.25862709 -1.00989032]]


In [43]:
array12 = np.random.randint(1, 7, size=(3, 4))
# low <= r < high의 정수들로 이루어진 난수
print(array12)

[[4 4 1 4]
 [3 1 4 5]
 [1 5 6 5]]


In [44]:
np.random.random_integers(1, 7, size=(3, 4))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 7 + 1) instead
  """Entry point for launching an IPython kernel.


array([[6, 1, 6, 1],
       [3, 7, 5, 2],
       [2, 2, 3, 6]])

In [45]:
# Numpy 인덱스, 인덱싱(인덱스를 이용해서 원소를 선택)
array = np.random.rand(10)
print(array)   # 1-D array

[0.98123305 0.50846401 0.14033759 0.29711777 0.10980212 0.51641035
 0.57880037 0.58135413 0.1776996  0.25505505]


In [51]:
print(array[9])
print(array[1:4])   # start <= i < end 범위 인덱스
print(array[:4])   # 시작 인덱스를 생략하면 기본값은 0
print(array[8:])   # 마지막 인덱스를 생략하면 기본값은 array의 끝까지
print(array[:])
print(array[-2:])

0.25505505233809234
[0.50846401 0.14033759 0.29711777]
[0.98123305 0.50846401 0.14033759 0.29711777]
[0.1776996  0.25505505]
[0.98123305 0.50846401 0.14033759 0.29711777 0.10980212 0.51641035
 0.57880037 0.58135413 0.1776996  0.25505505]
[0.1776996  0.25505505]


In [52]:
array = np.random.rand(3, 4)
print(array)

[[0.15713551 0.73730516 0.21519224 0.84474727]
 [0.69948144 0.51811744 0.20956124 0.74749196]
 [0.39686462 0.87696187 0.88230322 0.71912564]]


In [56]:
print(array[0, 0])   # [row index, column index]
print(array[1:3, 2:4])
print(array[:, 2:4])

0.1571355113918398
[[0.20956124 0.74749196]
 [0.88230322 0.71912564]]
[[0.21519224 0.84474727]
 [0.20956124 0.74749196]
 [0.88230322 0.71912564]]


In [59]:
# Numpy array의 인덱싱을 할 때 row 또는 column 인덱스를
# 숫자 1개만 준 경우, 2-D 배열이 1-D 배열로 바뀜
print(array[:, 0])   # (3,) 1-D array
print(array[0, :])   # (4,) 1-D array

[0.15713551 0.69948144 0.39686462]
[0.15713551 0.73730516 0.21519224 0.84474727]


In [61]:
# NumPy array에서 인덱싱을 할 때, 인덱스에 배열을 줄 수 있음
print(array[:, [0, 3]])
print(array[:, [0]])   # (3, 1) 2-D array

[[0.15713551 0.84474727]
 [0.69948144 0.74749196]
 [0.39686462 0.71912564]]
[[0.15713551]
 [0.69948144]
 [0.39686462]]


In [67]:
# boolean indexing : 논리값(True/False)들을 사용해서 필요한 원소들을 선택
array = np.random.randn(10)
print(array)

[ 0.10121014 -0.26194582  0.92460617 -0.60325344 -0.17434925  0.70497598
 -0.87703677 -0.68277285 -0.43205776  1.47033659]


In [68]:
array > 0

array([ True, False,  True, False, False,  True, False, False, False,
        True])

In [69]:
print(array[array > 0])

[0.10121014 0.92460617 0.70497598 1.47033659]


In [72]:
# boolean indexing을 할 때 &, |, ~ 연산자를 함께 사용할 수 있음
# 2개의 조건을 & 또는 |로 연결할 때는 반드시 ()를 사용해야 함
print(array[(array > 0.5) | (array < -0.5)])
print(array[(array < 0.5) & (array > -0.5)])

[ 0.92460617 -0.60325344  0.70497598 -0.87703677 -0.68277285  1.47033659]
[ 0.10121014 -0.26194582 -0.17434925 -0.43205776]


In [74]:
np.random.seed(1)   # 난수를 생성하는 결과를 재현할 수 있도록
array = np.random.randn(3, 3)
print(array)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [75]:
print(array > 0)

[[ True False False]
 [False  True False]
 [ True False  True]]


In [77]:
print(array[array > 0])
# 결과가 1-D array

[1.62434536 0.86540763 1.74481176 0.3190391 ]


In [82]:
print(array[[0, 2]])
print(array[[0, 2],])
print(array[[0, 2], :])
# 위의 세가지 인덱싱 방식은 같은 결과!

[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [85]:
print(array[[True, False, True]])

[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [88]:
X = np.arange(16).reshape(4, 4)
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [90]:
y = np.array([0, 0, 1, 1])
print(y)

[0 0 1 1]


In [91]:
print(X[y == 0])

[[0 1 2 3]
 [4 5 6 7]]
