In [2]:
import numpy as np

In [9]:
np.random.rand(4, 5, 3)

array([[[0.34345347, 0.07168796, 0.64819712],
        [0.01424931, 0.25107538, 0.70725717],
        [0.43445359, 0.89343314, 0.44250712],
        [0.7350972 , 0.5122568 , 0.61343129],
        [0.91348034, 0.17168497, 0.71694755]],

       [[0.68255059, 0.90282088, 0.28960085],
        [0.93100332, 0.56079928, 0.89241963],
        [0.171791  , 0.00160657, 0.83756849],
        [0.76794082, 0.20929853, 0.64249368],
        [0.87560202, 0.23683397, 0.99340636]],

       [[0.3320446 , 0.85535212, 0.21835294],
        [0.88940921, 0.72017021, 0.95162412],
        [0.21161421, 0.86904265, 0.73381729],
        [0.01294107, 0.771952  , 0.67550149],
        [0.3297379 , 0.84193308, 0.95673233]],

       [[0.76380918, 0.31281218, 0.3073837 ],
        [0.84955279, 0.60657882, 0.01576073],
        [0.14207876, 0.928682  , 0.48638637],
        [0.30508957, 0.41555253, 0.34847731],
        [0.14491496, 0.42106305, 0.66272857]]])

In [11]:
np.random.randn(3, 4, 2)

array([[[ 0.07083654, -0.41619853],
        [ 1.29934388, -0.33596176],
        [-0.34695404,  1.58114807],
        [ 1.13621902, -0.42488773]],

       [[-2.10249211,  0.4667535 ],
        [-0.87883168,  0.409903  ],
        [ 0.44195043,  1.2148602 ],
        [-1.14569344, -0.30025843]],

       [[-2.10215847, -2.03492119],
        [ 0.32340604,  1.37217801],
        [-1.93153801, -1.76278367],
        [-0.61156072,  1.58423093]]])

In [13]:
np.random.randint(1, 100, size=(3, 5, 2))

array([[[22, 85],
        [11,  6],
        [87, 40],
        [81, 99],
        [79,  6]],

       [[72,  4],
        [82, 84],
        [77, 63],
        [ 7,  4],
        [32, 96]],

       [[29,  1],
        [50, 79],
        [52, 20],
        [23, 89],
        [83, 97]]])

In [17]:
np.random.seed(100)

In [20]:
np.random.seed(100)
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [21]:
np.random.choice(100, size = (3, 4))

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [26]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[2. , 1.5],
       [1. , 3. ]])

In [27]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.10191676, 1.76214681, 2.05853156, 2.9137538 , 1.35164262],
       [1.23660567, 2.72589134, 1.14973376, 2.65018972, 2.67226363],
       [1.15078982, 1.02280158, 1.09684114, 1.71424542, 2.33138675],
       [1.02277922, 1.21583553, 2.8020262 , 2.58975752, 2.62292196]])

In [28]:
np.random.normal(size=(3, 4))

array([[ 1.31557418,  1.4789783 ,  0.22142626, -1.11789416],
       [-0.18499993, -0.43118745,  0.14253625, -1.49639345],
       [ 0.30687456, -0.04634723,  0.41714428, -0.60377052]])