In [1]:
import numpy as np

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


In [8]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
x[1,2]

7

In [14]:
x[0]

array([0, 1, 2, 3, 4])

In [15]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [18]:
x[1, 2, 1]

19

In [19]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
x[1:7:2]

array([1, 3, 5])

In [25]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
x[:1, :2]

array([[0, 1]])

In [30]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [31]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [32]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])