In [3]:
import numpy as np

In [4]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.74280897 0.33367107 0.14128569 0.91541276 0.20219564]
 [0.9183429  0.69264571 0.24222705 0.34668056 0.90019648]
 [0.58339702 0.84470866 0.47979479 0.94441015 0.93562771]]


In [5]:
np.add(x, y)

array([[ 0.74280897,  1.33367107,  2.14128569,  3.91541276,  4.20219564],
       [ 5.9183429 ,  6.69264571,  7.24222705,  8.34668056,  9.90019648],
       [10.58339702, 11.84470866, 12.47979479, 13.94441015, 14.93562771]])

In [6]:
print(y)

[[0.74280897 0.33367107 0.14128569 0.91541276 0.20219564]
 [0.9183429  0.69264571 0.24222705 0.34668056 0.90019648]
 [0.58339702 0.84470866 0.47979479 0.94441015 0.93562771]]


In [7]:
np.mean(y)

0.614893677904068

In [8]:
y.mean()

0.614893677904068

In [9]:
np.max(y)

0.9444101507476921

In [10]:
np.min(y)

0.14128568573418976

In [11]:
np.argmax(y)

13

In [12]:
np.argmin(y)

2

In [13]:
np.sum(y)

9.22340516856102

In [14]:
np.cumsum(y)

array([0.74280897, 1.07648004, 1.21776572, 2.13317848, 2.33537413,
       3.25371703, 3.94636274, 4.18858979, 4.53527035, 5.43546683,
       6.01886385, 6.86357251, 7.34336731, 8.28777746, 9.22340517])

In [16]:
z = np.random.randn(10)
print(z)

[-0.06627257 -1.46135409 -1.14622058 -1.53532009  2.94000966  0.04728755
 -0.79910185 -1.2197853  -1.3932972   0.39349128]


In [17]:
np.any(z > 0)

True

In [18]:
z = np.random.randn(10)
print(z)

[ 1.00114055 -1.15688676 -0.13345759  0.67218358  0.27686313  1.40455316
 -2.05544079 -1.36839612  0.88139281 -0.066334  ]


In [19]:
np.where(z > 0, z, 0)

array([1.00114055, 0.        , 0.        , 0.67218358, 0.27686313,
       1.40455316, 0.        , 0.        , 0.88139281, 0.        ])